import CryptoKit
import Foundation

/// The model metadata that travels beside a converted `.mlpackage`.
///
/// Everything the Swift embedder needs to run a model correctly — pooling,
/// query prefix, dims, max tokens, special-token ids, the pinned HF revision,
/// and a hash binding this manifest to one `.mlpackage` — is generated by the
/// conversion script and read here, so a model swap needs no Swift changes.
internal struct StowerModelManifest: Codable, Sendable {
    internal let modelID: String
    internal let hfRevision: String
    internal let fingerprint: String
    internal let dims: Int
    internal let pooling: String
    internal let queryPrefix: String
    internal let maxTokens: Int
    internal let padTokenID: Int
    internal let clsTokenID: Int
    internal let sepTokenID: Int
    internal let inputIDsName: String
    internal let attentionMaskName: String
    internal let outputName: String
    internal let mlpackage: String
    internal let mlpackageSHA256: String
    internal let tokenizerDir: String

    internal enum CodingKeys: String, CodingKey {
        case modelID = "model_id"
        case hfRevision = "hf_revision"
        case fingerprint
        case dims
        case pooling
        case queryPrefix = "query_prefix"
        case maxTokens = "max_tokens"
        case padTokenID = "pad_token_id"
        case clsTokenID = "cls_token_id"
        case sepTokenID = "sep_token_id"
        case inputIDsName = "input_ids_name"
        case attentionMaskName = "attention_mask_name"
        case outputName = "output_name"
        case mlpackage
        case mlpackageSHA256 = "mlpackage_sha256"
        case tokenizerDir = "tokenizer_dir"
    }

    /// Loads and decodes `manifest.json` from a model directory.
    internal static func load(from modelDirectory: URL) throws -> StowerModelManifest {
        let url = modelDirectory.appendingPathComponent("manifest.json")
        guard FileManager.default.fileExists(atPath: url.path) else {
            throw StowerEmbedderError.modelNotFound(path: modelDirectory.path)
        }
        do {
            return try JSONDecoder().decode(StowerModelManifest.self, from: Data(contentsOf: url))
        } catch {
            throw StowerEmbedderError.manifestUnreadable(path: url.path, detail: "\(error)")
        }
    }

    /// Throws if the on-disk `.mlpackage` no longer matches the manifest hash.
    ///
    /// A stale manifest beside a different package would silently select the
    /// wrong pooling or prefix; binding the two by hash closes that class.
    internal func verifyPackageHash(in modelDirectory: URL) throws {
        let packageURL = modelDirectory.appendingPathComponent(mlpackage)
        let actual = try Self.directoryFingerprint(of: packageURL)
        guard actual == mlpackageSHA256 else {
            throw StowerEmbedderError.packageHashMismatch(expected: mlpackageSHA256, actual: actual)
        }
    }

    /// Hashes a directory order-independently; mirrors the script's `sha256_dir`.
    internal static func directoryFingerprint(of root: URL) throws -> String {
        let fileManager = FileManager.default
        // Resolve symlinks up front: the default model path is a symlink, and the
        // enumerator yields real paths while an unresolved root would mis-trim the
        // relative path and silently change the hash (a gate-corrupting mismatch).
        let resolvedRoot = root.resolvingSymlinksInPath()
        guard
            let enumerator = fileManager.enumerator(
                at: resolvedRoot,
                includingPropertiesForKeys: [.isRegularFileKey]
            )
        else {
            throw StowerEmbedderError.manifestUnreadable(
                path: resolvedRoot.path,
                detail: "unreadable package"
            )
        }
        var entries: [(relative: String, hash: String)] = []
        for case let fileURL as URL in enumerator {
            let values = try fileURL.resourceValues(forKeys: [.isRegularFileKey])
            guard values.isRegularFile == true else { continue }
            let fileContents = try Data(contentsOf: fileURL)
            let hash = SHA256.hash(data: fileContents).map { String(format: "%02x", $0) }.joined()
            entries.append((relativePath(of: fileURL, under: resolvedRoot), hash))
        }
        entries.sort { $0.relative < $1.relative }
        var hasher = SHA256()
        for entry in entries {
            hasher.update(data: Data(entry.relative.utf8))
            hasher.update(data: Data([0]))
            hasher.update(data: Data(entry.hash.utf8))
            hasher.update(data: Data([10]))
        }
        return hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }

    private static func relativePath(of fileURL: URL, under root: URL) -> String {
        let rootPath = root.resolvingSymlinksInPath().standardizedFileURL.path
        let filePath = fileURL.resolvingSymlinksInPath().standardizedFileURL.path
        let trimmed = filePath.dropFirst(rootPath.count).drop(while: { $0 == "/" })
        return String(trimmed)
    }
}
